[package]
name = "invisible_fun"
version = "0.1.0"
edition = "2024"

[dependencies]
failure = "0.1.8"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
tiny_http = "0.12.0"
