[package]
name = "invisible_fun"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
tiny_http = "0.12.0"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
fun-html = "1.8.0"
